[build-system]
requires = ["setuptools >= 77.0.3"]
build-backend = "setuptools.build_meta"

[project]
name = "rapid_hansard"
license = "GPL-3.0-or-later"
dynamic = ["version"]
requires-python = ">=3.12"
dependencies = [
    "lxml"
]

[project.optional-dependencies]
download_hansard = [
    "selenium",
    "requests"
]

[project.urls]
Homepage = "https://rapid-community-data-lab.github.io/"
Repository = "https://github.com/rapid-community-data-lab/australian_federal_parliament"
Issues = "https://github.com/rapid-community-data-lab/australian_federal_parliament/issues"

[tool.setuptools.dynamic]
version = {attr = "rapid_hansard.__version__"}
